// --- THE DATABASE ---
const masterList = [
    // --- BOLLYWOOD MOVIES ---
    { title: "3 Idiots", type: "Movie", industry: "Bollywood", context: "Cast: Aamir Khan, Kareena Kapoor" },
    { title: "Sholay", type: "Movie", industry: "Bollywood", context: "Iconic: Gabbar Singh, Jai & Veeru" },
    { title: "Tere Naam", type: "Movie", industry: "Bollywood", context: "Cast: Salman Khan (Middle Part Hair)" },
    { title: "Munna Bhai M.B.B.S.", type: "Movie", industry: "Bollywood", context: "Cast: Sanjay Dutt, Arshad Warsi" },
    { title: "Barfi!", type: "Movie", industry: "Bollywood", context: "Cast: Ranbir Kapoor, Priyanka Chopra" },
    { title: "Lagaan", type: "Movie", industry: "Bollywood", context: "Scene: Cricket Match" },
    { title: "PK", type: "Movie", industry: "Bollywood", context: "Cast: Aamir Khan (Alien)" },
    { title: "Dabangg", type: "Movie", industry: "Bollywood", context: "Cast: Salman Khan (Belt Shake)" },
    { title: "Kuch Kuch Hota Hai", type: "Movie", industry: "Bollywood", context: "Cast: SRK, Kajol, Rani" },
    { title: "Bhool Bhulaiyaa", type: "Movie", industry: "Bollywood", context: "Character: Manjulika" },
    { title: "Dilwale Dulhania Le Jayenge", type: "Movie", industry: "Bollywood", context: "Scene: Train Station (DDLJ)" },
    // --- 100 MORE BOLLYWOOD MOVIES (No Sequels) ---
    { title: "Karan Arjun", type: "Movie", industry: "Bollywood", context: "Dialogue: Mere Karan Arjun Aayenge" },
    { title: "Hum Aapke Hain Koun..!", type: "Movie", industry: "Bollywood", context: "Iconic: Tuffy the Dog & Slingshot" },
    { title: "Dil To Pagal Hai", type: "Movie", industry: "Bollywood", context: "Cast: SRK, Madhuri, Karisma (Dance)" },
    { title: "Baazigar", type: "Movie", industry: "Bollywood", context: "Dialogue: Haar ke jeetne wale ko..." },
    { title: "Darr", type: "Movie", industry: "Bollywood", context: "Dialogue: K-K-K-Kiran" },
    { title: "Raja Hindustani", type: "Movie", industry: "Bollywood", context: "Character: Taxi Driver (Aamir Khan)" },
    { title: "Pardes", type: "Movie", industry: "Bollywood", context: "Song: I Love My India" },
    { title: "Border", type: "Movie", industry: "Bollywood", context: "Scene: Sand, War, Sunny Deol" },
    { title: "Ishq", type: "Movie", industry: "Bollywood", context: "Scene: Aamir & Ajay (Monkey/Pipe)" },
    { title: "Gupt", type: "Movie", industry: "Bollywood", context: "Genre: Suspense/Killer (Bobby Deol)" },
    { title: "Kuch Kuch Hota Hai", type: "Movie", industry: "Bollywood", context: "Cast: SRK, Kajol, Rani (Friendship band)" },
    { title: "Soldier", type: "Movie", industry: "Bollywood", context: "Cast: Bobby Deol, Preity Zinta" },
    { title: "Taal", type: "Movie", industry: "Bollywood", context: "Music: A.R. Rahman (Aishwarya Rai)" },
    { title: "Biwi No.1", type: "Movie", industry: "Bollywood", context: "Cast: Salman Khan, Karisma, Sushmita" },
    { title: "Kaho Naa... Pyaar Hai", type: "Movie", industry: "Bollywood", context: "Step: The Hrithik Roshan Air Punch" },
    { title: "Mohabbatein", type: "Movie", industry: "Bollywood", context: "Prop: Violin / Gurukul" },
    { title: "Gadar: Ek Prem Katha", type: "Movie", industry: "Bollywood", context: "Scene: Sunny Deol pulling Handpump" },
    { title: "Devdas", type: "Movie", industry: "Bollywood", context: "Character: Drunk lover (SRK)" },
    { title: "Kal Ho Naa Ho", type: "Movie", industry: "Bollywood", context: "Scene: Reading the blank diary" },
    { title: "Koi... Mil Gaya", type: "Movie", industry: "Bollywood", context: "Character: Jadoo (Alien)" },
    { title: "Veer-Zaara", type: "Movie", industry: "Bollywood", context: "Cast: SRK (Pilot/Prisoner), Preity Zinta" },
    { title: "Swades", type: "Movie", industry: "Bollywood", context: "Scene: Generating Electricity (Bulb)" },
    { title: "Bunty Aur Babli", type: "Movie", industry: "Bollywood", context: "Characters: Two Thieves (Abhishek/Rani)" },
    { title: "Rang De Basanti", type: "Movie", industry: "Bollywood", context: "Cast: Aamir Khan (DJ), Freedom Fighters" },
    { title: "Krrish", type: "Movie", industry: "Bollywood", context: "Prop: Black Mask (Superhero)" },
    { title: "Don", type: "Movie", industry: "Bollywood", context: "Dialogue: Don ko pakadna mushkil..." },
    { title: "Chak De! India", type: "Movie", industry: "Bollywood", context: "Sport: Women's Hockey" },
    { title: "Om Shanti Om", type: "Movie", industry: "Bollywood", context: "Scene: Wave to the fans (Reincarnation)" },
    { title: "Jab We Met", type: "Movie", industry: "Bollywood", context: "Character: Talkative Geet (Kareena)" },
    { title: "Welcome", type: "Movie", industry: "Bollywood", context: "Character: Majnu Bhai (Painting)" },
    { title: "Singh Is Kinng", type: "Movie", industry: "Bollywood", context: "Costume: Turban & Bling" },
    { title: "Ghajini", type: "Movie", industry: "Bollywood", context: "Look: Bald head with scars/Tattoos" },
    { title: "Rab Ne Bana Di Jodi", type: "Movie", industry: "Bollywood", context: "Character: Surinder Sahni (Moustache)" },
    { title: "Wanted", type: "Movie", industry: "Bollywood", context: "Action: Collar Shake (Salman Khan)" },
    { title: "Zindagi Na Milegi Dobara", type: "Movie", industry: "Bollywood", context: "Scene: Running with Bulls / Skydiving" },
    { title: "Rockstar", type: "Movie", industry: "Bollywood", context: "Prop: Guitar (Ranbir Kapoor)" },
    { title: "Agneepath", type: "Movie", industry: "Bollywood", context: "Villain: Kancha Cheena (Sanjay Dutt)" },
    { title: "Kahaani", type: "Movie", industry: "Bollywood", context: "Character: Pregnant Woman Search (Vidya)" },
    { title: "Vicky Donor", type: "Movie", industry: "Bollywood", context: "Topic: Sperm Donation (Ayushmann)" },
    { title: "Rowdy Rathore", type: "Movie", industry: "Bollywood", context: "Action: Twirling Moustache" },
    { title: "Cocktail", type: "Movie", industry: "Bollywood", context: "Cast: Saif, Deepika, Diana Penty" },
    { title: "English Vinglish", type: "Movie", industry: "Bollywood", context: "Character: Sridevi learning English" },
    { title: "Student of the Year", type: "Movie", industry: "Bollywood", context: "Cast: Alia, Varun, Sidharth (Debut)" },
    { title: "Yeh Jawaani Hai Deewani", type: "Movie", industry: "Bollywood", context: "Character: Bunny (Trekking/Travel)" },
    { title: "Chennai Express", type: "Movie", industry: "Bollywood", context: "Accent: Meenamma (Tangaballi)" },
    { title: "Bhaag Milkha Bhaag", type: "Movie", industry: "Bollywood", context: "Action: Running (Farhan Akhtar)" },
    { title: "Queen", type: "Movie", industry: "Bollywood", context: "Scene: Solo Honeymoon in Paris" },
    { title: "2 States", type: "Movie", industry: "Bollywood", context: "Theme: North Indian vs South Indian Marriage" },
    { title: "Piku", type: "Movie", industry: "Bollywood", context: "Topic: Constipation / Road Trip" },
    { title: "Bajrangi Bhaijaan", type: "Movie", industry: "Bollywood", context: "Character: Mute Girl (Munni)" },
    { title: "Bajirao Mastani", type: "Movie", industry: "Bollywood", context: "Character: Peshwa Warrior (Ranveer)" },
    { title: "Sultan", type: "Movie", industry: "Bollywood", context: "Sport: Wrestling (Salman Khan)" },
    { title: "Dangal", type: "Movie", industry: "Bollywood", context: "Sport: Wrestling (Phogat Sisters)" },
    { title: "Baahubali", type: "Movie", industry: "Bollywood", context: "Scene: Lifting the Shivling / Katappa" },
    { title: "Secret Superstar", type: "Movie", industry: "Bollywood", context: "Character: Burqa wearing singer" },
    { title: "Padmaavat", type: "Movie", industry: "Bollywood", context: "Villain: Khilji (Eating meat wildly)" },
    { title: "Sanju", type: "Movie", industry: "Bollywood", context: "Biopic: Sanjay Dutt's Life" },
    { title: "Andhadhun", type: "Movie", industry: "Bollywood", context: "Character: Blind Pianist (Ayushmann)" },
    { title: "Simmba", type: "Movie", industry: "Bollywood", context: "Dialogue: Tell me something I don't know" },
    { title: "Gully Boy", type: "Movie", industry: "Bollywood", context: "Song: Apna Time Aayega (Rapper)" },
    { title: "Kabir Singh", type: "Movie", industry: "Bollywood", context: "Character: Angry Doctor / Beard" },
    { title: "War", type: "Movie", industry: "Bollywood", context: "Cast: Hrithik vs Tiger Shroff" },
    { title: "Tanhaji", type: "Movie", industry: "Bollywood", context: "Genre: Historical War (Ajay Devgn)" },
    { title: "Pushpa: The Rise", type: "Movie", industry: "Bollywood", context: "Action: Hand under beard (Thaggedhe Le)" },
    { title: "RRR", type: "Movie", industry: "Bollywood", context: "Song: Naatu Naatu Dance" },
    { title: "K.G.F", type: "Movie", industry: "Bollywood", context: "Dialogue: Salam Rocky Bhai" },
    { title: "Brahmastra", type: "Movie", industry: "Bollywood", context: "Power: Fire/Agni (Ranbir Kapoor)" },
    { title: "Pathaan", type: "Movie", industry: "Bollywood", context: "Song: Jhoome Jo Pathaan (Salute)" },
    { title: "Drishyam", type: "Movie", industry: "Bollywood", context: "Quote: 2nd October Satsang" },
    { title: "Jawan", type: "Movie", industry: "Bollywood", context: "Look: Bandaged Face / Bald SRK" },
    { title: "Animal", type: "Movie", industry: "Bollywood", context: "Scene: Machine Gun / Papa" },
    { title: "Dunki", type: "Movie", industry: "Bollywood", context: "Topic: Illegal Immigration (Donkey Flight)" },
    { title: "Rocky Aur Rani...", type: "Movie", industry: "Bollywood", context: "Theme: Switching Households" },
    { title: "12th Fail", type: "Movie", industry: "Bollywood", context: "Theme: IPS Exam Struggle" },
    { title: "Stree", type: "Movie", industry: "Bollywood", context: "Dialogue: O Stree Kal Aana" },
    { title: "Housefull", type: "Movie", industry: "Bollywood", context: "Scene: Too many people in one room" },
    { title: "Golmaal: Fun Unlimited", type: "Movie", industry: "Bollywood", context: "Action: Finger Spin (Ajay Devgn)" },
    { title: "Dhamaal", type: "Movie", industry: "Bollywood", context: "Scene: Finding the big 'W'" },
    { title: "Hera Pheri", type: "Movie", industry: "Bollywood", context: "Character: Babu Rao (Paresh Rawal)" },
    { title: "Chup Chup Ke", type: "Movie", industry: "Bollywood", context: "Scene: Shahid pretending to be mute" },
    { title: "Bhagam Bhag", type: "Movie", industry: "Bollywood", context: "Cast: Akshay, Govinda" },
    { title: "Malamaal Weekly", type: "Movie", industry: "Bollywood", context: "Plot: Lottery Ticket" },
    { title: "Garam Masala", type: "Movie", industry: "Bollywood", context: "Plot: Managing 3 Girlfriends" },
    { title: "No Entry", type: "Movie", industry: "Bollywood", context: "Hook: No Entry (Salman/Anil)" },
    { title: "Partner", type: "Movie", industry: "Bollywood", context: "Character: Love Guru (Salman)" },
    { title: "Heyy Babyy", type: "Movie", industry: "Bollywood", context: "Plot: Three bachelors find a baby" },
    { title: "Main Hoon Na", type: "Movie", industry: "Bollywood", context: "Action: SRK Matrix Bend" },
    { title: "Kabhi Khushi Kabhie Gham", type: "Movie", industry: "Bollywood", context: "Scene: Mother sensing son (Thali)" },
    { title: "Andaz Apna Apna", type: "Movie", industry: "Bollywood", context: "Villain: Crime Master Gogo" },
    { title: "Taare Zameen Par", type: "Movie", industry: "Bollywood", context: "Topic: Dyslexic Child / Painting" },
    { title: "Pad Man", type: "Movie", industry: "Bollywood", context: "Prop: Sanitary Pad" },
    { title: "Toilet: Ek Prem Katha", type: "Movie", industry: "Bollywood", context: "Social Issue: Building a Toilet" },
    { title: "Uri: The Surgical Strike", type: "Movie", industry: "Bollywood", context: "Dialogue: How's the Josh?" },
    { title: "Kantara", type: "Movie", industry: "Bollywood", context: "Sound: The 'Whoaa' Scream" },
    //{ title: "Crew", type: "Movie", industry: "Bollywood", context: "Cast: Tabu, Kareena, Kriti (Air Hostess)" },
   // { title: "Munjya", type: "Movie", industry: "Bollywood", context: "Character: CGI Creature (Ghost)" },
    { title: "Fighter", type: "Movie", industry: "Bollywood", context: "Cast: Hrithik (Air Force Pilot)" },
    { title: "Hum Dil De Chuke Sanam", type: "Movie", industry: "Bollywood", context: "Song: Nimbooda Nimbooda" },
    { title: "Hungama", type: "Movie", industry: "Bollywood", context: "Genre: Confusion Comedy" },
    { title: "Dhoom", type: "Movie", industry: "Bollywood", context: "Prop: Fast Bikes (John Abraham)" },
    { title: "Race", type: "Movie", industry: "Bollywood", context: "Genre: Twist & Turns Thriller" },
    { title: "Kick", type: "Movie", industry: "Bollywood", context: "Action: Walking across train tracks" },
    { title: "Bodyguard", type: "Movie", industry: "Bollywood", context: "Action: Biceps / Shadow" },
    { title: "Namastey London", type: "Movie", industry: "Bollywood", context: "Cast: Akshay Kumar, Katrina Kaif" },
    { title: "Wake Up Sid", type: "Movie", industry: "Bollywood", context: "Theme: Lazy rich boy wakes up" },
    { title: "Delhi Belly", type: "Movie", industry: "Bollywood", context: "Song: Bhaag D.K. Bose" },
    { title: "Fukrey", type: "Movie", industry: "Bollywood", context: "Character: Choocha (Dreams)" },
    //{ title: "Sarfarosh", type: "Movie", industry: "Bollywood", context: "Cast: Aamir Khan (Cop), Naseeruddin Shah" },
   // { title: "Khakee", type: "Movie", industry: "Bollywood", context: "Cast: Amitabh, Akshay, Aishwarya" },
    { title: "Company", type: "Movie", industry: "Bollywood", context: "Topic: Underworld Gangs (Vivek Oberoi)" },
    // --- 100 NEW BOLLYWOOD MOVIES (Govinda Era to Now) ---
    { title: "Coolie No. 1", type: "Movie", industry: "Bollywood", context: "Role: Porter/Coolie (Govinda)" },
    { title: "Hero No. 1", type: "Movie", industry: "Bollywood", context: "Scene: Painting the street / Govinda Style" },
    { title: "Dulhe Raja", type: "Movie", industry: "Bollywood", context: "Setting: Hotel Business (Raveena Tandon)" },
    { title: "Haseena Maan Jaayegi", type: "Movie", industry: "Bollywood", context: "Dialouge: What is mobile number?" },
    { title: "Bade Miyan Chote Miyan", type: "Movie", industry: "Bollywood", context: "Cast: Amitabh & Govinda (Double Roles)" },
    { title: "Saajan Chale Sasural", type: "Movie", industry: "Bollywood", context: "Plot: Managing two wives" },
    { title: "Judwaa", type: "Movie", industry: "Bollywood", context: "Action: Butt Slap / Double Role" },
    { title: "Mr. India", type: "Movie", industry: "Bollywood", context: "Prop: Invisible Watch / Mogambo" },
    { title: "Chachi 420", type: "Movie", industry: "Bollywood", context: "Role: Man dressed as old woman" },
    { title: "Nayak: The Real Hero", type: "Movie", industry: "Bollywood", context: "Plot: One Day Chief Minister" },
    { title: "Sooryavansham", type: "Movie", industry: "Bollywood", context: "Meme: Heera Thakur / Eating Kheer" },
    { title: "Khalnayak", type: "Movie", industry: "Bollywood", context: "Song: Choli Ke Peeche / Jail Escape" },
    { title: "Rangeela", type: "Movie", industry: "Bollywood", context: "Character: Munna (Tapori Style)" },
    { title: "Satya", type: "Movie", industry: "Bollywood", context: "Character: Bhiku Mhatre / Mumbai Gangster" },
    { title: "Vaastav", type: "Movie", industry: "Bollywood", context: "Dialogue: 50 Tola Sona (Gold Chain)" },
    { title: "Dil Chahta Hai", type: "Movie", industry: "Bollywood", context: "Scene: Goa Road Trip / 3 Friends" },
    { title: "Lakshya", type: "Movie", industry: "Bollywood", context: "Scene: Army / Climbing Mountain Peak" },
    { title: "Rehnaa Hai Terre Dil Mein", type: "Movie", industry: "Bollywood", context: "Character: Maddy / Phone Lover" },
    { title: "Saathiya", type: "Movie", industry: "Bollywood", context: "Scene: Bike accident on bridge" },
    { title: "Hum Tum", type: "Movie", industry: "Bollywood", context: "Theme: Cartoon Characters" },
    { title: "Fanaa", type: "Movie", industry: "Bollywood", context: "Role: Blind Girl / Tourist Guide" },
    { title: "My Name Is Khan", type: "Movie", industry: "Bollywood", context: "Dialogue: My name is Khan and I am not..." },
    { title: "Ghajini", type: "Movie", industry: "Bollywood", context: "Action: Memory Loss / Tattoos" },
    { title: "Aitraaz", type: "Movie", industry: "Bollywood", context: "Role: Female Villain (Priyanka/Kareena)" },
    { title: "Dostana", type: "Movie", industry: "Bollywood", context: "Plot: Pretending to be Gay" },
    { title: "Fashion", type: "Movie", industry: "Bollywood", context: "Action: Ramp Walk / Modeling" },
    { title: "Paa", type: "Movie", industry: "Bollywood", context: "Role: Amitabh as a kid (Progeria)" },
    { title: "OMG – Oh My God!", type: "Movie", industry: "Bollywood", context: "Plot: Suing God in Court" },
    { title: "Special 26", type: "Movie", industry: "Bollywood", context: "Scene: Fake CBI Raid" },
    { title: "Baby", type: "Movie", industry: "Bollywood", context: "Genre: Spy / Terrorist Catching" },
    { title: "Holiday", type: "Movie", industry: "Bollywood", context: "Character: Sleeper Cells / Soldier" },
    { title: "Airlift", type: "Movie", industry: "Bollywood", context: "Plot: Evacuating Indians from Kuwait" },
    { title: "Rustom", type: "Movie", industry: "Bollywood", context: "Role: Naval Officer / Court Case" },
    { title: "Toilet: Ek Prem Katha", type: "Movie", industry: "Bollywood", context: "Social Issue: Building a Toilet" },
    { title: "Pad Man", type: "Movie", industry: "Bollywood", context: "Prop: Sanitary Napkin" },
    { title: "Mary Kom", type: "Movie", industry: "Bollywood", context: "Sport: Women's Boxing" },
    { title: "Neerja", type: "Movie", industry: "Bollywood", context: "Role: Air Hostess / Hijack" },
    { title: "Udta Punjab", type: "Movie", industry: "Bollywood", context: "Look: Long Hair / Drugs / Rockstar" },
    { title: "Haider", type: "Movie", industry: "Bollywood", context: "Look: Bald Head (Shahid Kapoor)" },
    { title: "Ludo", type: "Movie", industry: "Bollywood", context: "Theme: Board Game / Multiple Stories" },
    { title: "Chhichhore", type: "Movie", industry: "Bollywood", context: "Setting: College Hostel Life" },
    { title: "Super 30", type: "Movie", industry: "Bollywood", context: "Role: Teacher / Math on Blackboard" },
    { title: "M.S. Dhoni: The Untold Story", type: "Movie", industry: "Bollywood", context: "Action: Helicopter Shot / Cricket" },
    { title: "83", type: "Movie", industry: "Bollywood", context: "Sport: Winning World Cup (Ranveer)" },
    { title: "Shershaah", type: "Movie", industry: "Bollywood", context: "Dialogue: Yeh Dil Maange More" },
    { title: "Mimi", type: "Movie", industry: "Bollywood", context: "Plot: Surrogate Mother (Pregnant)" },
    { title: "Gangubai Kathiawadi", type: "Movie", industry: "Bollywood", context: "Action: Namaste from forehead (Alia)" },
    { title: "Bhool Bhulaiyaa 2", type: "Movie", industry: "Bollywood", context: "Cast: Kartik Aaryan / Manjulika" },
    { title: "Pyaar Kiya To Darna Kya", type: "Movie", industry: "Bollywood", context: "Song: O O Jaane Jaana (Shirtless)" },
    { title: "Hum Saath-Saath Hain", type: "Movie", industry: "Bollywood", context: "Action: ABCDEFGHI... (Alphabet Song)" },
    { title: "Vivah", type: "Movie", industry: "Bollywood", context: "Meme: Jal Lijiye (Water)" },
    { title: "Main Prem Ki Diwani Hoon", type: "Movie", industry: "Bollywood", context: "Meme: Overacting (Hrithik/Kareena)" },
    { title: "Mujhse Shaadi Karogi", type: "Movie", industry: "Bollywood", context: "Step: Towel Dance" },
    { title: "Jaan-E-Mann", type: "Movie", industry: "Bollywood", context: "Cast: Salman, Akshay, Preity" },
    { title: "Khiladi 786", type: "Movie", industry: "Bollywood", context: "Action: Breaking things with hand" },
    { title: "Tees Maar Khan", type: "Movie", industry: "Bollywood", context: "Song: Sheila Ki Jawani" },
    { title: "Happy New Year", type: "Movie", industry: "Bollywood", context: "Plot: Robbery at Dance Competition" },
    { title: "Fan", type: "Movie", industry: "Bollywood", context: "Role: SRK as Crazy Fan (Aryan Khanna)" },
    { title: "Zero", type: "Movie", industry: "Bollywood", context: "Role: Short Man / Dwarf (SRK)" },
    { title: "Tubelight", type: "Movie", industry: "Bollywood", context: "Action: Shoes around neck" },
    { title: "Bajrangi Bhaijaan", type: "Movie", industry: "Bollywood", context: "Character: Mute Girl / Hanumanchalisa" },
    { title: "Ek Tha Tiger", type: "Movie", industry: "Bollywood", context: "Role: RAW Agent / Scarf" },
    { title: "Sultan", type: "Movie", industry: "Bollywood", context: "Sport: Wrestling / Paunch" },
    { title: "Bharat", type: "Movie", industry: "Bollywood", context: "Look: Old Man / Partition" },
    { title: "Dabangg", type: "Movie", industry: "Bollywood", context: "Action: Belt Shake / Sunglasses back" },
    { title: "Ready", type: "Movie", industry: "Bollywood", context: "Song: Dhinka Chika (Pockets)" },
    { title: "Bodyguard", type: "Movie", industry: "Bollywood", context: "Action: Biceps check / Phone" },
    { title: "Kick", type: "Movie", industry: "Bollywood", context: "Action: Walking across Train Tracks" },
    { title: "Jai Ho", type: "Movie", industry: "Bollywood", context: "Action: Drawing on Paper (Help 3 people)" },
    { title: "Prem Ratan Dhan Payo", type: "Movie", industry: "Bollywood", context: "Step: Finger near eye (Title Song)" },
    { title: "Pyaar To Hona Hi Tha", type: "Movie", industry: "Bollywood", context: "Scene: Airplane Fear (Kajol)" },
    { title: "Gupt", type: "Movie", industry: "Bollywood", context: "Genre: Murder Mystery (Bobby Deol)" },
    { title: "Josh", type: "Movie", industry: "Bollywood", context: "Gang: Eagles vs Scorpions" },
    { title: "Baadshah", type: "Movie", industry: "Bollywood", context: "Role: Detective / X-Ray Goggles" },
    { title: "Koyla", type: "Movie", industry: "Bollywood", context: "Role: Mute Servant (SRK)" },
    { title: "Pardes", type: "Movie", industry: "Bollywood", context: "Song: Do Dil Mil Rahe Hain" },
    { title: "Yes Boss", type: "Movie", industry: "Bollywood", context: "Song: Main Koi Aisa Geet Gaoon" },
    { title: "Raju Ban Gaya Gentleman", type: "Movie", industry: "Bollywood", context: "Theme: Office / Architect" },
    { title: "Chalte Chalte", type: "Movie", industry: "Bollywood", context: "Role: Truck Driver (SRK)" },
    { title: "Kaante", type: "Movie", industry: "Bollywood", context: "Plot: 6 Men robbing a bank" },
    { title: "Musafir", type: "Movie", industry: "Bollywood", context: "Look: Anil Kapoor / Toothpick / Bald" },
    { title: "Shootout at Lokhandwala", type: "Movie", industry: "Bollywood", context: "Song: Ganpat (Drunk dance)" },
    { title: "Once Upon a Time in Mumbaai", type: "Movie", industry: "Bollywood", context: "Look: Sultan Mirza (All White)" },
    { title: "Singham", type: "Movie", industry: "Bollywood", context: "Action: Lion Claw Slap (Ajay Devgn)" },
    { title: "Bol Bachchan", type: "Movie", industry: "Bollywood", context: "Dialogue: English speaking (Ajay Devgn)" },
    { title: "Son of Sardaar", type: "Movie", industry: "Bollywood", context: "Theme: Sikhs / Turbans / Horse" },
    { title: "Total Dhamaal", type: "Movie", industry: "Bollywood", context: "Scene: Zoo / Animals" },
    { title: "De De Pyaar De", type: "Movie", industry: "Bollywood", context: "Plot: Old man, Young girlfriend" },
    { title: "Drishyam ", type: "Movie", industry: "Bollywood", context: "Prop: Shovel / Police Station" },
          
    { title: "Satyaprem Ki Katha", type: "Movie", industry: "Bollywood", context: "Cast: Kartik Aaryan, Kiara" },
    { title: "Dream Girl", type: "Movie", industry: "Bollywood", context: "Role: Man talking in female voice (Pooja)" },
    { title: "Bala", type: "Movie", industry: "Bollywood", context: "Look: Bald / Wig" },
      { title: "Badhaai Ho", type: "Movie", industry: "Bollywood", context: "Plot: Parents get pregnant" },
 

    // --- BANGLA MOVIES ---
    { title: "Beder Meye Josna", type: "Movie", industry: "Bangla", context: "Cast: Ilias Kanchan, Anju Ghosh" },
    { title: "Hothat Brishti", type: "Movie", industry: "Bangla", context: "Cast: Ferdous (Basudeb)" },
    { title: "Dipu Number Two", type: "Movie", industry: "Bangla", context: "Classic: Muhammed Zafar Iqbal Story" },
    { title: "Monpura", type: "Movie", industry: "Bangla", context: "Cast: Chanchal Chowdhury" },
    { title: "Aynabaji", type: "Movie", industry: "Bangla", context: "Character: Sharafat Karim Ayna" },
    { title: "Srabon Megher Din", type: "Movie", industry: "Bangla", context: "Director: Humayun Ahmed" },
    { title: "Bachelor", type: "Movie", industry: "Bangla", context: "Cast: Mostofa Sarwar Farooki Film" },
    { title: "Ammajaan", type: "Movie", industry: "Bangla", context: "Cast: Manna (Iconic Dialogue)" },
    { title: "Shoshur Bari Zindabad", type: "Movie", industry: "Bangla", context: "Cast: Riaz, Shabnur" },
    // --- 50 SUPER MAINSTREAM BANGLA MOVIES (90s Kids Nostalgia) ---
    { title: "Keyamat Theke Keyamat", type: "Movie", industry: "Bangla", context: "Act: Dead bodies on both sides (Salman-Moushumi)" },
    { title: "Sujon Sokhi", type: "Movie", industry: "Bangla", context: "Song: Sob Sokhire Paar Korite (Boat)" },
    { title: "Shopner Thikana", type: "Movie", industry: "Bangla", context: "Song: O Sathire (Salman Shah Style)" },
    { title: "Denmohor", type: "Movie", industry: "Bangla", context: "Theme: Wedding / Kabin Nama" },
    { title: "Anondo Osru", type: "Movie", industry: "Bangla", context: "Character: Mad/Crazy Lover (Salman Shah)" },
    { title: "Molla Barir Bou", type: "Movie", industry: "Bangla", context: "Character: Scary Father-in-law (ATM Shamsuzzaman)" },
    { title: "Hajar Bochhor Dhore", type: "Movie", industry: "Bangla", context: "Scene: Old man lighting lantern (Riaz)" },
    { title: "Shoshur Bari Zindabad", type: "Movie", industry: "Bangla", context: "Action: Thumbs up (Riaz-Shabnur)" },
    { title: "Moner Majhe Tumi", type: "Movie", industry: "Bangla", context: "Song: Akashe Batashe (Riaz-Purnima)" },
    { title: "Hridoyer Kotha", type: "Movie", industry: "Bangla", context: "Scene: Attempting suicide / Eating poison" },
    { title: "Koti Takar Kabin", type: "Movie", industry: "Bangla", context: "Theme: Rich Girl Poor Boy (Shakib Khan)" },
    { title: "Chacchu", type: "Movie", industry: "Bangla", context: "Dialogue: Chacchu! (Dipjol Voice)" },
    { title: "Dadi Ma", type: "Movie", industry: "Bangla", context: "Role: Old Grandmother (Monwara Begum)" },
    { title: "Ammajan", type: "Movie", industry: "Bangla", context: "Scene: Saluting Mother / Knife (Manna)" },
    { title: "Kosto", type: "Movie", industry: "Bangla", context: "Action: Breaking chains / Manna Rage" },
    { title: "Abbajan", type: "Movie", industry: "Bangla", context: "Action: Manna respecting Father" },
    { title: "Srabon Megher Din", type: "Movie", industry: "Bangla", context: "Song: Ekta Chilo Sonar Konna" },
    { title: "Dui Duari", type: "Movie", industry: "Bangla", context: "Character: Mysterious Man (Humayun Faridi)" },
    { title: "Shyamol Chhaya", type: "Movie", industry: "Bangla", context: "Scene: Boat Journey / War 1971" },
    { title: "Agune Poroshmoni", type: "Movie", industry: "Bangla", context: "Scene: War / Commando Operation" },
    { title: "Bachelor", type: "Movie", industry: "Bangla", context: "Song: Ami To Preme Porini (Hasan)" },
    { title: "Third Person Singular Number", type: "Movie", industry: "Bangla", context: "Character: Convict (Mosharraf Karim)" },
    { title: "Television", type: "Movie", industry: "Bangla", context: "Prop: TV / Imagine turning knob" },
    { title: "Aynabaji", type: "Movie", industry: "Bangla", context: "Character: Changing faces (Chanchal)" },
    { title: "Monpura", type: "Movie", industry: "Bangla", context: "Song: Jao Pakhi Bolo Tare (Island)" },
    { title: "Swapnojal", type: "Movie", industry: "Bangla", context: "Scene: Fishing Net (Jal) / Pori Moni" },
    { title: "Hawa", type: "Movie", industry: "Bangla", context: "Song: Sada Sada Kala Kala (Mandolin)" },
    { title: "Poran", type: "Movie", industry: "Bangla", context: "Character: Local Gangster (Sariful Razz)" },
    { title: "Surongo", type: "Movie", industry: "Bangla", context: "Action: Digging a tunnel (Afran Nisho)" },
    { title: "Priya Amar Priya", type: "Movie", industry: "Bangla", context: "Song: Chokher Poloke (Shakib Khan)" },
    { title: "Bhalobasha Bhalobasha", type: "Movie", industry: "Bangla", context: "Action: Heart shape with hands (Riaz)" },
    { title: "Mayer Morjada", type: "Movie", industry: "Bangla", context: "Theme: Touching Mother's Feet" },
    { title: "Pita Mata Sontan", type: "Movie", industry: "Bangla", context: "Scene: Family Crying Drama" },
    { title: "Dipu Number Two", type: "Movie", industry: "Bangla", context: "Action: Showing 2 Fingers (Zafar Iqbal)" },
    { title: "Amar Bondhu Rashed", type: "Movie", industry: "Bangla", context: "Scene: 1971 War / Map" },
    { title: "Matir Moyna", type: "Movie", industry: "Bangla", context: "Scene: Madrasa / Bird (Moyna)" },
    { title: "Ontore Ontore", type: "Movie", industry: "Bangla", context: "Song: Ekhane Dujone Nirjone (Salman)" },
    { title: "Tomake Chai", type: "Movie", industry: "Bangla", context: "Action: Pointing 'I Want You'" },
    { title: "Mayer Doa", type: "Movie", industry: "Bangla", context: "Action: Praying (Manna Style)" },
    { title: "Tej", type: "Movie", industry: "Bangla", context: "Action: Angry Manna / Fighting" },
    { title: "Ghetuputra Komola", type: "Movie", industry: "Bangla", context: "Scene: Dancing Boy / Humayun Ahmed" },
    { title: "Daruchini Dip", type: "Movie", industry: "Bangla", context: "Action: Island Trip / Riaz" },
    { title: "Chader Pahar", type: "Movie", industry: "Bangla", context: "Action: Lion Attack / Mountain (Dev)" },
    { title: "Beder Meye Josna", type: "Movie", industry: "Bangla", context: "Action: Snake Charmer Flute (Bin)" },
    { title: "Khacha", type: "Movie", industry: "Bangla", context: "Action: Bird Cage" },
    { title: "Oggatonama", type: "Movie", industry: "Bangla", context: "Prop: Coffin (Dead Body)" },
    { title: "Shonibar Bikel", type: "Movie", industry: "Bangla", context: "Scene: Hostage Situation / Cafe" },
    { title: "Rehana Maryam Noor", type: "Movie", industry: "Bangla", context: "Role: Strict Teacher / Doctor" },
    { title: "Damal", type: "Movie", industry: "Bangla", context: "Sport: Football in 1971" },
    { title: "Toofan", type: "Movie", industry: "Bangla", context: "Action: Machine Gun / Shakib Swagger" },
    // --- SONGS ---
    { title: "Lungi Dance", type: "Song", industry: "Bollywood", context: "Hook: All the Rajini fans... Thalaiva!" },
    { title: "Chaiyya Chaiyya", type: "Song", industry: "Bollywood", context: "Scene: Dancing on a Train" },
    { title: "Kala Chashma", type: "Song", industry: "Bollywood", context: "Hook: Tenu kala chashma jachda ae" },
    { title: "Tumpa Shona", type: "Song", industry: "Bangla", context: "Hook: Tumpa shona... humba humba" },
    { title: "O Bondhu Lal Golap", type: "Song", industry: "Bangla", context: "Artist: Sabina Yasmin / Manna Lip-sync" },
    { title: "Tip Tip Barsa Pani", type: "Song", industry: "Bollywood", context: "Scene: Yellow Saree / Rain" },
    { title: "Nagin Dance", type: "Song", industry: "General", context: "Action: Snake Dance on Floor" },
    { title: "Bondhu Tin Din", type: "Song", industry: "Bangla", context: "Hook: Bondhu tin din tor barite gelam..." },
    { title: "Ek Do Teen", type: "Song", industry: "Bollywood", context: "Hook: Tera karoon gin gin intezaar" }
    // --- 100 BOLLYWOOD SONGS (Govinda to Latest) ---
    ,{ title: "Main To Raste Se Ja Raha Tha", type: "Song", industry: "Bollywood", context: "Action: Eating Bhelpuri / Mirchi" },
    { title: "Kisi Disco Mein Jaaye", type: "Song", industry: "Bollywood", context: "Action: Pointing up (Disco)" },
    { title: "Sona Kitna Sona Hai", type: "Song", industry: "Bollywood", context: "Action: Pointing to Gold / Sleeping" },
    { title: "Akhiyon Se Goli Maare", type: "Song", industry: "Bollywood", context: "Action: Gunshot with fingers near eyes" },
    { title: "What Is Mobile Number", type: "Song", industry: "Bollywood", context: "Action: Dialing a phone" },
    { title: "Sarkailo Khatiya", type: "Song", industry: "Bollywood", context: "Action: Pushing a bed (Khatiya)" },
    { title: "Tan Tana Tan Tan", type: "Song", industry: "Bollywood", context: "Action: Talking on a telephone" },
    { title: "O O Jaane Jaana", type: "Song", industry: "Bollywood", context: "Action: Playing Guitar / Shirtless" },
    { title: "Jeene Ke Hain Chaar Din", type: "Song", industry: "Bollywood", context: "Step: The Towel Dance" },
    { title: "Chalo Ishq Ladaaye", type: "Song", industry: "Bollywood", context: "Action: Fist fighting & Loving" },
    { title: "Tujhe Dekha To", type: "Song", industry: "Bollywood", context: "Step: Open Arms (SRK Pose)" },
    { title: "Mehndi Laga Ke Rakhna", type: "Song", industry: "Bollywood", context: "Action: Showing palms (Henna)" },
    { title: "Yeh Kaali Kaali Aankhen", type: "Song", industry: "Bollywood", context: "Action: Pointing to black eyes" },
    { title: "Ruk Ja O Dil Deewane", type: "Song", industry: "Bollywood", context: "Action: Piano playing step" },
    { title: "Bole Chudiyan", type: "Song", industry: "Bollywood", context: "Action: Pointing to wrist/bangles" },
    { title: "You Are My Soniya", type: "Song", industry: "Bollywood", context: "Step: Pointing index fingers" },
    { title: "Shava Shava", type: "Song", industry: "Bollywood", context: "Step: Hand wave from mouth (Amitabh)" },
    { title: "Koi Kahe Kehta Rahe", type: "Song", industry: "Bollywood", context: "Action: Pointing to others / Gossiping" },
    { title: "Ek Pal Ka Jeena", type: "Song", industry: "Bollywood", context: "Step: Air Punch (Hrithik)" },
    { title: "Kaho Naa... Pyaar Hai", type: "Song", industry: "Bollywood", context: "Step: Rowing the boat step" },
    { title: "Bumbro Bumbro", type: "Song", industry: "Bollywood", context: "Step: Hand flip (Mission Kashmir)" },
    { title: "Dola Re Dola", type: "Song", industry: "Bollywood", context: "Step: Side-to-side classical hands" },
    { title: "Kajra Re", type: "Song", industry: "Bollywood", context: "Step: Hand over eyes (Bunty Aur Babli)" },
    { title: "Beedi Jalaile", type: "Song", industry: "Bollywood", context: "Action: Lighting a matchstick" },
    { title: "Jhoom Barabar Jhoom", type: "Song", industry: "Bollywood", context: "Step: Shake hands in air" },
    { title: "Mauja Hi Mauja", type: "Song", industry: "Bollywood", context: "Step: Thumbs up dance" },
    { title: "Nagada Nagada", type: "Song", industry: "Bollywood", context: "Action: Playing Drums" },
    { title: "Desi Girl", type: "Song", industry: "Bollywood", context: "Action: Pulling Saree Pallu" },
    { title: "Dhan Te Nan", type: "Song", industry: "Bollywood", context: "Action: Running fast" },
    { title: "Masakali", type: "Song", industry: "Bollywood", context: "Action: Pigeon flying from head" },
    { title: "All Izz Well", type: "Song", industry: "Bollywood", context: "Action: Whistling" },
    { title: "Zoobi Doobi", type: "Song", industry: "Bollywood", context: "Action: Rain & Umbrella" },
    { title: "Sheila Ki Jawani", type: "Song", industry: "Bollywood", context: "Step: Hands behind head" },
    { title: "Munni Badnaam Hui", type: "Song", industry: "Bollywood", context: "Action: Touching cheeks + Shame" },
    { title: "Dhinka Chika", type: "Song", industry: "Bollywood", context: "Step: Hands in pockets" },
    { title: "Chammak Challo", type: "Song", industry: "Bollywood", context: "Action: Pulling a scarf sideways" },
    { title: "Chikni Chameli", type: "Song", industry: "Bollywood", context: "Action: Lighting match on waist" },
    { title: "Ooh La La", type: "Song", industry: "Bollywood", context: "Step: Hip bump (Dirty Picture)" },
    { title: "Tumhi Ho Bandhu", type: "Song", industry: "Bollywood", context: "Step: Hands up twist (Cocktail)" },
    { title: "Badtameez Dil", type: "Song", industry: "Bollywood", context: "Action: Slapping heart" },
    { title: "Balam Pichkari", type: "Song", industry: "Bollywood", context: "Action: Using Water Gun" },
    { title: "1234 Get On The Dance Floor", type: "Song", industry: "Bollywood", context: "Action: Counting 1 to 4 on fingers" },
    { title: "Sunny Sunny", type: "Song", industry: "Bollywood", context: "Line: Aaj Blue Hai Pani" },
    { title: "Baby Doll", type: "Song", industry: "Bollywood", context: "Action: Rocking a baby in arms" },
    { title: "London Thumakda", type: "Song", industry: "Bollywood", context: "Action: Tea + Shake hips" },
    { title: "Chittiyaan Kalaiyaan", type: "Song", industry: "Bollywood", context: "Action: Showing Wrists" },
    { title: "Gallan Goodiyaan", type: "Song", industry: "Bollywood", context: "Context: Family Group Dance" },
    { title: "Tukur Tukur", type: "Song", industry: "Bollywood", context: "Action: Staring without blinking" },
    { title: "Malhari", type: "Song", industry: "Bollywood", context: "Step: Warrior / Bajirao Step" },
    { title: "Kar Gayi Chull", type: "Song", industry: "Bollywood", context: "Action: Driving a car" },
    { title: "Nachde Ne Saare", type: "Song", industry: "Bollywood", context: "Action: Wedding Dance" },
    { title: "Nashe Si Chadh Gayi", type: "Song", industry: "Bollywood", context: "Action: Acting Drunk/Dizzy" },
    { title: "The Breakup Song", type: "Song", industry: "Bollywood", context: "Action: Thumbs down / Headphones" },
    { title: "Ghoomar", type: "Song", industry: "Bollywood", context: "Action: Spinning in circles" },
    { title: "Dilbar", type: "Song", industry: "Bollywood", context: "Action: Drawing Heart on Chest" },
    { title: "Aankh Maare", type: "Song", industry: "Bollywood", context: "Action: Winking Eye" },
    { title: "Coca Cola", type: "Song", industry: "Bollywood", context: "Action: Drinking from bottle" },
    { title: "Apna Time Aayega", type: "Song", industry: "Bollywood", context: "Action: Tapping Wrist Watch" },
    { title: "Ghungroo", type: "Song", industry: "Bollywood", context: "Action: Pointing to Ankles" },
    { title: "Bala", type: "Song", industry: "Bollywood", context: "Action: Touching Bald Head" },
    { title: "Garmi", type: "Song", industry: "Bollywood", context: "Action: Fanning yourself (Too Hot)" },
    { title: "Muqabla", type: "Song", industry: "Bollywood", context: "Step: Michael Jackson Slide" },
    { title: "Burj Khalifa", type: "Song", industry: "Bollywood", context: "Action: Pointing up / Tall Building" },
    { title: "Naach Meri Rani", type: "Song", industry: "Bollywood", context: "Action: Adjusting Crown" },
    { title: "Paani Paani", type: "Song", industry: "Bollywood", context: "Action: Drinking lots of water" },
    { title: "Bijli Bijli", type: "Song", industry: "Bollywood", context: "Action: Getting Electric Shock" },
    { title: "Srivalli", type: "Song", industry: "Bollywood", context: "Step: Dragging one slipper" },
    { title: "Sami Sami", type: "Song", industry: "Bollywood", context: "Step: Hip shake (Pushpa)" },
    { title: "Naatu Naatu", type: "Song", industry: "Bollywood", context: "Step: Leg Kicking (RRR)" },
    { title: "Kesariya", type: "Song", industry: "Bollywood", context: "Step: Finger Heart (Love Storiya)" },
    { title: "Jhoome Jo Pathaan", type: "Song", industry: "Bollywood", context: "Step: Salute + Hair Flip" },
    { title: "Besharam Rang", type: "Song", industry: "Bollywood", context: "Action: Acting Shy + Color" },
    { title: "Tere Vaste", type: "Song", industry: "Bollywood", context: "Action: Pulling Moon (Chand) down" },
    { title: "Main Yahaan Hoon", type: "Song", industry: "Bollywood", context: "Step: Open Arms (Veer Zaara)" },
    { title: "Jumme Ki Raat", type: "Song", industry: "Bollywood", context: "Step: Pulling coat with teeth" },
    { title: "Swag Se Swagat", type: "Song", industry: "Bollywood", context: "Step: Salute / Swag" },
    { title: "Zingaat", type: "Song", industry: "Bollywood", context: "Step: Jumping Wildly" },
    { title: "High Heels", type: "Song", industry: "Bollywood", context: "Action: Walking on tiptoes" },
    { title: "Abhi Toh Party Shuru Hui Hai", type: "Song", industry: "Bollywood", context: "Action: Looking at Watch" },
    { title: "Chaar Botal Vodka", type: "Song", industry: "Bollywood", context: "Action: Holding 4 Bottles" },
    { title: "Saturday Saturday", type: "Song", industry: "Bollywood", context: "Action: Pointing to Calendar" },
    { title: "Selfie Le Le Re", type: "Song", industry: "Bollywood", context: "Action: Taking a Selfie" },
    { title: "Tattad Tattad", type: "Song", industry: "Bollywood", context: "Step: Brushing hair (Ranveer)" },
    { title: "Andekhi Anjaani", type: "Song", industry: "Bollywood", context: "Action: Lifting veil" },
    { title: "Kabootar Ja Ja Ja", type: "Song", industry: "Bollywood", context: "Action: Flying Bird" },
    { title: "Pardesi Pardesi", type: "Song", industry: "Bollywood", context: "Action: Waving Goodbye to Train" },
    { title: "Soldier Soldier", type: "Song", industry: "Bollywood", context: "Action: Saluting" },
    { title: "Yeh Ladka Hai Deewana", type: "Song", industry: "Bollywood", context: "Action: Acting Crazy" },
    { title: "Dhoom Machale", type: "Song", industry: "Bollywood", context: "Action: Revving a Bike" },
    { title: "Aati Kya Khandala", type: "Song", industry: "Bollywood", context: "Action: Lighting Matchstick on tongue" },
    { title: "Pappu Can't Dance", type: "Song", industry: "Bollywood", context: "Action: Pointing to a 'Pappu' friend" },
    { title: "Galliyan", type: "Song", industry: "Bollywood", context: "Action: Walking on street" },
    { title: "Chura Ke Dil Mera", type: "Song", industry: "Bollywood", context: "Action: Stealing from chest" },
    { title: "Tu Cheez Badi Hai Mast", type: "Song", industry: "Bollywood", context: "Action: Pointing to face (Mask)" },
    { title: "Ole Ole", type: "Song", industry: "Bollywood", context: "Step: Bobby Deol Hand Roll" },
    { title: "Main Nikla Gaddi Leke", type: "Song", industry: "Bollywood", context: "Action: Riding a Motorcycle" },
    { title: "Le Gayi", type: "Song", industry: "Bollywood", context: "Action: Whistling (Karisma)" },
    { title: "Aunty Ki Ghanti", type: "Song", industry: "Bollywood", context: "Action: Ringing Doorbell" },
    { title: "Hookah Bar", type: "Song", industry: "Bollywood", context: "Action: Smoking Hookah" },
    { title: "Fevicol Se", type: "Song", industry: "Bollywood", context: "Action: Stuck to wall/chair" },
    { title: "Gade Te Niche", type: "Song", industry: "Bollywood", context: "Action: Car + Down" },
    { title: "Slow Motion", type: "Song", industry: "Bollywood", context: "Action: Moving in Slow Mo" },
    { title: "Hud Hud Dabangg", type: "Song", industry: "Bollywood", context: "Step: Belt Buckle Shake" },
    { title: "Seeti Maar", type: "Song", industry: "Bollywood", context: "Step: Whistling + Underarm" },
    { title: "Jag Ghoomeya", type: "Song", industry: "Bollywood", context: "Step: Spinning on floor" },
    { title: "Tauba Tauba", type: "Song", industry: "Bollywood", context: "Step: Vicky Kaushal Leg Slide" },
    // --- 100 NEW BOLLYWOOD SONGS (No Repeats) ---
    { title: "My Name Is Lakhan", type: "Song", industry: "Bollywood", context: "Step: One-Two-Ka-Four Hand Move" },
    { title: "Saat Samundar Paar", type: "Song", industry: "Bollywood", context: "Action: Swimming / 7 Fingers" },
    { title: "Jumma Chumma De De", type: "Song", industry: "Bollywood", context: "Action: Kissing Request / Amitabh Step" },
    { title: "Tamma Tamma Loge", type: "Song", industry: "Bollywood", context: "Step: Head collisions / Disco Finger" },
    { title: "Hawa Hawai", type: "Song", industry: "Bollywood", context: "Action: Fan / Wind (Sridevi)" },
    { title: "Papa Kehte Hain", type: "Song", industry: "Bollywood", context: "Action: Proud Father / Guitar" },
    { title: "Ghar Aaja Pardesi", type: "Song", industry: "Bollywood", context: "Action: Come Home / Waving" },
    { title: "Didi Tera Devar Deewana", type: "Song", industry: "Bollywood", context: "Action: Slingshot to butt / Fake Belly" },
    { title: "Chana Jor Garam", type: "Song", industry: "Bollywood", context: "Action: Eating street food" },
    { title: "Mere Rang Mein Rangne Wali", type: "Song", industry: "Bollywood", context: "Action: Coloring someone" },
    { title: "Tu Tu Tu Tu Tara", type: "Song", industry: "Bollywood", context: "Action: Pointing finger (You You You)" },
    { title: "Husn Hai Suhana", type: "Song", industry: "Bollywood", context: "Step: Washing face / 'Suhana' gesture" },
    { title: "Mere Khwabon Mein", type: "Song", industry: "Bollywood", context: "Action: Sleeping / Dreaming" },
    { title: "Ho Gaya Hai Tujhko To Pyar", type: "Song", industry: "Bollywood", context: "Action: Realization / DDLJ moment" },
    { title: "Saajanji Ghar Aaye", type: "Song", industry: "Bollywood", context: "Action: Groom Arriving / Accordion" },
    { title: "Nimbooda Nimbooda", type: "Song", industry: "Bollywood", context: "Action: Squeezing Lemon / Aishwarya Dance" },
    { title: "Doli Taro Dhol Baje", type: "Song", industry: "Bollywood", context: "Action: Playing Dandiya Sticks" },
    { title: "Chand Chupa Badal Mein", type: "Song", industry: "Bollywood", context: "Action: Hiding Moon (Face) with Hands" },
    { title: "Apun Bola Tu Meri Laila", type: "Song", industry: "Bollywood", context: "Action: Tapori style pointing" },
    { title: "M Bole To", type: "Song", industry: "Bollywood", context: "Action: Spelling letters / Munnabhai" },
    { title: "Na Tum Jano Na Hum", type: "Song", industry: "Bollywood", context: "Action: Shrugging shoulders (Don't know)" },
    { title: "Yeh Ladka Hai Allah", type: "Song", industry: "Bollywood", context: "Action: Pointing Up (Allah) + Boy" },
    { title: "Mahi Ve", type: "Song", industry: "Bollywood", context: "Step: Hand Roll Disco Step (Kal Ho Naa Ho)" },
    { title: "It's The Time To Disco", type: "Song", industry: "Bollywood", context: "Step: Pointing fingers up-down" },
    { title: "Kal Ho Naa Ho (Title)", type: "Song", industry: "Bollywood", context: "Action: Sad / Arms open wide" },
    { title: "Pretty Woman", type: "Song", industry: "Bollywood", context: "Action: Hand on cheek (Beautiful)" },
    { title: "Idhar Chala Main Udhar Chala", type: "Song", industry: "Bollywood", context: "Action: Swaying left and right" },
    { title: "Jaadoo Jaadoo", type: "Song", industry: "Bollywood", context: "Action: Wiggling fingers (Magic)" },
    { title: "Main Hoon Na", type: "Song", industry: "Bollywood", context: "Action: The SRK Matrix Backward Bend" },
    { title: "Tumse Milke Dilka Jo Haal", type: "Song", industry: "Bollywood", context: "Action: Qawwali Clapping" },
    { title: "Gori Gori", type: "Song", industry: "Bollywood", context: "Action: Pointing to fair skin / Party" },
    { title: "Chale Jaise Hawayein", type: "Song", industry: "Bollywood", context: "Action: Wind blowing hair" },
    { title: "Dilbara", type: "Song", industry: "Bollywood", context: "Action: Calling out / Dhoom style" },
    { title: "Nach Baliye", type: "Song", industry: "Bollywood", context: "Action: Couple Dancing" },
    { title: "Namak Ishq Ka", type: "Song", industry: "Bollywood", context: "Action: Sprinkling Salt" },
    { title: "Bol Na Halke Halke", type: "Song", industry: "Bollywood", context: "Action: Whispering in ear" },
    { title: "Ticket To Hollywood", type: "Song", industry: "Bollywood", context: "Action: Airplane / Ticket" },
    { title: "Chak De India", type: "Song", industry: "Bollywood", context: "Action: Swinging Hockey Stick" },
    { title: "Tum Se Hi", type: "Song", industry: "Bollywood", context: "Action: Pointing 'Only You' (Rain)" },
    { title: "Yeh Ishq Hai", type: "Song", industry: "Bollywood", context: "Action: Shivering in Cold / Snow" },
    { title: "Aao Milo Chalo", type: "Song", industry: "Bollywood", context: "Action: Walking together / Road trip" },
    { title: "Bhootni Ke", type: "Song", industry: "Bollywood", context: "Action: Acting like a Ghost / Drunk" },
    { title: "Jee Karda", type: "Song", industry: "Bollywood", context: "Action: Jumping aggressively / Rock" },
    { title: "Maa Da Laadla", type: "Song", industry: "Bollywood", context: "Action: Spoiled Brat / Mama's Boy" },
    { title: "Shut Up & Bounce", type: "Song", industry: "Bollywood", context: "Action: Finger on lips + Jumping" },
    { title: "Haule Haule", type: "Song", industry: "Bollywood", context: "Action: Slow motion hand movement" },
    { title: "Dance Pe Chance", type: "Song", industry: "Bollywood", context: "Action: Teaching dance steps" },
    { title: "Tujh Mein Rab Dikhta Hai", type: "Song", industry: "Bollywood", context: "Action: Namaste / Praying to partner" },
    { title: "Genda Phool (Delhi 6)", type: "Song", industry: "Bollywood", context: "Action: Marigold flower / Big fabric" },
    { title: "Emosanal Attyachaar", type: "Song", industry: "Bollywood", context: "Action: Fake crying / Brass Band" },
    { title: "Gal Mitthi Mitthi", type: "Song", industry: "Bollywood", context: "Action: Eating sweets / Talking" },
    { title: "Ainvayi Ainvayi", type: "Song", industry: "Bollywood", context: "Action: Wedding Dance / Eating" },
    { title: "Dum Maaro Dum", type: "Song", industry: "Bollywood", context: "Action: Smoking pipe / Guitar" },
    { title: "Character Dheela", type: "Song", industry: "Bollywood", context: "Action: Loosening shirt collar" },
    { title: "Sadi Gali", type: "Song", industry: "Bollywood", context: "Action: Pointing to 'Our Street'" },
    { title: "Anarkali Disco Chali", type: "Song", industry: "Bollywood", context: "Action: Walking to Disco" },
    { title: "Pungi", type: "Song", industry: "Bollywood", context: "Action: Playing snake charmer flute" },
    { title: "Daaru Desi", type: "Song", industry: "Bollywood", context: "Action: Drunk friends hugging" },
    { title: "Kukkad", type: "Song", industry: "Bollywood", context: "Action: Rooster / Chicken head bob" },
    { title: "Balma", type: "Song", industry: "Bollywood", context: "Action: 786 Hand step / Akshay" },
    { title: "Tu Mere Agal Bagal Hai", type: "Song", industry: "Bollywood", context: "Action: Side-to-Side step (Sasha)" },
    { title: "Malang", type: "Song", industry: "Bollywood", context: "Action: Circus / Acrobatics" },
    { title: "Kamli", type: "Song", industry: "Bollywood", context: "Action: Removing layers of clothes / Crazy" },
    { title: "Party All Night", type: "Song", industry: "Bollywood", context: "Action: Drinking / Yo Yo Honey Singh" },
    { title: "Samjhawan", type: "Song", industry: "Bollywood", context: "Action: Explaining / Sad face" },
    { title: "Engine Ki Seeti", type: "Song", industry: "Bollywood", context: "Action: Pulling Train Whistle / Bum shake" },
    { title: "Bang Bang", type: "Song", industry: "Bollywood", context: "Action: Finger Guns shooting" },
    { title: "Tu Meri", type: "Song", industry: "Bollywood", context: "Action: Pointing 'You are Mine'" },
    { title: "India Waale", type: "Song", industry: "Bollywood", context: "Action: Salute / Hands in air" },
    { title: "Lovely", type: "Song", industry: "Bollywood", context: "Action: Calling 'Mohini' / Pole dance" },
    { title: "Superman", type: "Song", industry: "Bollywood", context: "Action: Flying Pose (Tevar)" },
    { title: "Desi Look", type: "Song", industry: "Bollywood", context: "Action: Adjusting Sunglasses" },
    { title: "Banno", type: "Song", industry: "Bollywood", context: "Action: Swagger Bride" },
    { title: "Tung Tung Baje", type: "Song", industry: "Bollywood", context: "Action: Playing instrument / Jumping" },
    { title: "Gulaabo", type: "Song", industry: "Bollywood", context: "Action: Holding Rose / Drunk walk" },
    { title: "Gerua", type: "Song", industry: "Bollywood", context: "Action: Airplane arms / Orange cloth" },
    { title: "Let's Nacho", type: "Song", industry: "Bollywood", context: "Action: Squat Dance" },
    { title: "Chitta Ve", type: "Song", industry: "Bollywood", context: "Action: Sniffing powder / Headbanging" },
    { title: "Udta Punjab", type: "Song", industry: "Bollywood", context: "Action: Flying like bird" },
    { title: "Baby Ko Bass Pasand Hai", type: "Song", industry: "Bollywood", context: "Action: Hand low (Bass) + Rocking Baby" },
    { title: "440 Volt", type: "Song", industry: "Bollywood", context: "Action: Touching wire / Shock" },
    { title: "Sau Aasmaan", type: "Song", industry: "Bollywood", context: "Action: Looking at Sky / Math (100)" },
    { title: "Ae Dil Hai Mushkil", type: "Song", industry: "Bollywood", context: "Action: Singing into mic / Crying" },
    { title: "Cutiepie", type: "Song", industry: "Bollywood", context: "Action: Pinching Cheeks" },
    { title: "Dangal", type: "Song", industry: "Bollywood", context: "Action: Wrestling / Thigh Slap" },
    { title: "Humma Humma", type: "Song", industry: "Bollywood", context: "Action: Hip Thrust / Sensual" },
    { title: "Laila Main Laila", type: "Song", industry: "Bollywood", context: "Action: Item Dance / SRK walks in" },
    { title: "Zaalima", type: "Song", industry: "Bollywood", context: "Action: Desert sand / Love" },
    { title: "Tamma Tamma Again", type: "Song", industry: "Bollywood", context: "Action: Disco Finger (Remix)" },
    { title: "Badri Ki Dulhania", type: "Song", industry: "Bollywood", context: "Action: Throwing Holi Colors" },
    { title: "Cheez Badi", type: "Song", industry: "Bollywood", context: "Action: Mask on face" },
    { title: "Main Tera Boyfriend", type: "Song", industry: "Bollywood", context: "Action: Pointing 'Me' then 'You' + Flex" },
    { title: "Radio", type: "Song", industry: "Bollywood", context: "Action: Tuning a Radio knob" },
    { title: "Galti Se Mistake", type: "Song", industry: "Bollywood", context: "Action: Hand on mouth (Oops) / Jagga Step" },
    { title: "Mere Rashke Qamar", type: "Song", industry: "Bollywood", context: "Action: Looking at Moon / Drumming" },
    { title: "Hawa Hawa", type: "Song", industry: "Bollywood", context: "Action: Wind blowing / Arjun Kapoor Step" },
    { title: "Lagdi Hai Thaai", type: "Song", industry: "Bollywood", context: "Action: Slapping Thighs" },
    { title: "Chalti Hai Kya 9 Se 12", type: "Song", industry: "Bollywood", context: "Action: Checking Watch / Walking" },
    { title: "Oonchi Hai Building", type: "Song", industry: "Bollywood", context: "Action: Looking up high / Lift" },
    { title: "Dil Diyan Gallan", type: "Song", industry: "Bollywood", context: "Action: Drawing Heart on floor" },
    { title: "Khalibali", type: "Song", industry: "Bollywood", context: "Action: Shaking Shoulders Aggressively" },
    { title: "Kamariya", type: "Song", industry: "Bollywood", context: "Action: Waist Shake (Stree)" },
    { title: "First Class", type: "Song", industry: "Bollywood", context: "Action: Thumbs Up / Kalank Step" },
    { title: "Psycho Saiyaan", type: "Song", industry: "Bollywood", context: "Action: Acting Crazy" },
    { title: "Jai Jai Shivshankar", type: "Song", industry: "Bollywood", context: "Action: Holi Dance / Hrithik-Tiger" },
    { title: "Sauda Khara Khara", type: "Song", industry: "Bollywood", context: "Action: Bhangra / Nagin Hands (Good Newwz)" },
    //{ title: "Chandigarh Mein", type: "Song", industry: "Bollywood", context: "Action: Pointing North" },
    { title: "Genda Phool (Badshah)", type: "Song", industry: "Bollywood", context: "Action: Flower / Bengalis" },
    //{ title: "Oo Antava", type: "Song", industry: "Bollywood", context: "Action: Stroking Beard / Pushpa Item" },
    //{ title: "Bhool Bhulaiyaa 2 (Title)", type: "Song", industry: "Bollywood", context: "Action: Zig-Zag Leg Glide" },
    { title: "Show Me The Thumka", type: "Song", industry: "Bollywood", context: "Action: Hip Shake (TJMM)" },
    { title: "What Jhumka", type: "Song", industry: "Bollywood", context: "Action: Earring falling / Alia Step" },
    //{ title: "Kaavaalaa", type: "Song", industry: "Bollywood", context: "Action: Rolling Hips (Jailer)" },
   // { title: "Not Ramaiya Vastavaiya", type: "Song", industry: "Bollywood", context: "Action: Wagging Finger 'No' / SRK" },
    //{ title: "Akhiyaan Gulaab", type: "Song", industry: "Bollywood", context: "Action: Rose + Eyes" },
    //{ title: "Teri Baaton Mein Aisa", type: "Song", industry: "Bollywood", context: "Action: Robot Dance / Confusion" },
    //{ title: "Aaj Ki Raat", type: "Song", industry: "Bollywood", context: "Action: Pointing Down (Tonight/Stree 2)" },
    { title: "Aayi Nai", type: "Song", industry: "Bollywood", context: "Action: Shaking Head 'No' (Stree 2)" },
    // --- 100+ SANGEET & PARTY VIBE SONGS (Soni De Nakhre Style) ---
    { title: "Soni De Nakhre", type: "Song", industry: "Bollywood", context: "Step: Hip shake side-to-side (Partner)" },
    { title: "Navrai Majhi", type: "Song", industry: "Bollywood", context: "Action: Bride / Saree / Wedding (English Vinglish)" },
    { title: "Senorita", type: "Song", industry: "Bollywood", context: "Action: Clapping / Spanish Flamenco (ZNMD)" },
    { title: "Desi Boyz", type: "Song", industry: "Bollywood", context: "Action: Flexing Muscles / Make Some Noise" },
    { title: "Subha Hone Na De", type: "Song", industry: "Bollywood", context: "Action: Pointing finger up / No Morning" },
    { title: "Right Here Right Now", type: "Song", industry: "Bollywood", context: "Action: Pointing down (Abhishek Bachchan)" },
    { title: "Twist", type: "Song", industry: "Bollywood", context: "Step: Twisting feet (Love Aaj Kal)" },
    { title: "Aahun Aahun", type: "Song", industry: "Bollywood", context: "Action: Guitar / Punjabi Rock" },
    { title: "Mauja Hi Mauja", type: "Song", industry: "Bollywood", context: "Step: Thumbs up dance (Jab We Met)" },
    { title: "Nagada Sang Dhol", type: "Song", industry: "Bollywood", context: "Action: Garba / Playing Drums (Ram Leela)" },
    { title: "Ainvayi Ainvayi", type: "Song", industry: "Bollywood", context: "Action: Eating / Wedding Dance" },
    { title: "Baari Barsi", type: "Song", industry: "Bollywood", context: "Action: Bhangra / Band Baaja Baaraat" },
    { title: "Laung Da Lashkara", type: "Song", industry: "Bollywood", context: "Action: Pointing to Nose (Nose ring)" },
    { title: "Sadi Gali", type: "Song", industry: "Bollywood", context: "Action: Pointing to 'Our Lane' (Tanu Weds Manu)" },
    { title: "Rum & Whisky", type: "Song", industry: "Bollywood", context: "Action: Drinking / Drunk Dance" },
    { title: "Radha", type: "Song", industry: "Bollywood", context: "Action: Dancing on the dance floor (SOTY)" },
    { title: "Disco Deewane", type: "Song", industry: "Bollywood", context: "Action: Pointing up / Disco Ball" },
    { title: "Ishq Wala Love", type: "Song", industry: "Bollywood", context: "Action: Drawing Heart in air / Slow" },
    { title: "Vele", type: "Song", industry: "Bollywood", context: "Action: Lazy / Hanging out with friends" },
    { title: "Lat Lag Gayee", type: "Song", industry: "Bollywood", context: "Action: Addiction / Finger to head" },
    { title: "Party On My Mind", type: "Song", industry: "Bollywood", context: "Action: Pointing to Head / Party" },
    { title: "Dilliwaali Girlfriend", type: "Song", industry: "Bollywood", context: "Action: Red skirt / Delhi" },
    { title: "Ghagra", type: "Song", industry: "Bollywood", context: "Action: Swirling skirt (Madhuri/Ranbir)" },
    { title: "Chingam Chabake", type: "Song", industry: "Bollywood", context: "Action: Chewing Gum / Blowing bubble" },
    { title: "Tooh", type: "Song", industry: "Bollywood", context: "Action: Bumping hips (Butt)" },
    { title: "Tune Maari Entriyaan", type: "Song", industry: "Bollywood", context: "Action: Hearing bells ringing in heart" },
    { title: "Asalaam-e-Ishqum", type: "Song", industry: "Bollywood", context: "Action: Salute / Qawwali style" },
    { title: "Punjabi Wedding Song", type: "Song", industry: "Bollywood", context: "Action: Bhangra / Drum beating" },
    { title: "Iski Uski", type: "Song", industry: "Bollywood", context: "Action: Pointing Him/Her / 2 States" },
    { title: "Locha-E-Ulfat", type: "Song", industry: "Bollywood", context: "Action: Confusion / Making faces (2 States)" },
    { title: "Mast Magan", type: "Song", industry: "Bollywood", context: "Action: Devotion / Namaste" },
    { title: "Offo", type: "Song", industry: "Bollywood", context: "Action: Facepalm / 'Oh God'" },
    { title: "Gallan Goodiyaan", type: "Song", industry: "Bollywood", context: "Context: One-take song / Family Dance" },
    //{ title: "Pehli Baar", type: "Song", industry: "Bollywood", context: "Action: Splashing water (Dil Dhadakne Do)" },
    { title: "Sooraj Dooba Hain", type: "Song", industry: "Bollywood", context: "Action: Sunset / Driving with glasses" },
    { title: "Matargashti", type: "Song", industry: "Bollywood", context: "Action: Imitating Dev Anand (Tamasha)" },
    { title: "High Heels", type: "Song", industry: "Bollywood", context: "Action: Walking on tiptoes" },
    { title: "Let's Nacho", type: "Song", industry: "Bollywood", context: "Action: Squatting Dance Step" },
    { title: "Nachde Ne Saare", type: "Song", industry: "Bollywood", context: "Action: Family Sangeet / Catwalk" },
    { title: "Sau Aasmaan", type: "Song", industry: "Bollywood", context: "Action: Looking at Sky / Math (100)" },
    { title: "Ude Dil Befikre", type: "Song", industry: "Bollywood", context: "Action: Flying Heart / Paris" },
    { title: "The Humma Song", type: "Song", industry: "Bollywood", context: "Action: Sensual / Hip Thrust" },
    { title: "Enna Sona", type: "Song", industry: "Bollywood", context: "Action: Admiring beauty / OK Jaanu" },
    { title: "Humsafar", type: "Song", industry: "Bollywood", context: "Action: Walking together / Badrinath" },
    { title: "Main Tera Boyfriend", type: "Song", industry: "Bollywood", context: "Action: Flexing Biceps / Pointing You" },
    { title: "Sweety Tera Drama", type: "Song", industry: "Bollywood", context: "Action: Acting Dramatic / Fan" },
    { title: "Hawa Hawa", type: "Song", industry: "Bollywood", context: "Step: Arjun Kapoor Side Step" },
    { title: "Dil Diyan Gallan", type: "Song", industry: "Bollywood", context: "Action: Drawing Heart on floor (Tiger)" },
    { title: "Swag Se Swagat", type: "Song", industry: "Bollywood", context: "Action: Salute / Swag" },
    { title: "Khalibali", type: "Song", industry: "Bollywood", context: "Action: Shaking Shoulders Aggressively" },
    { title: "Kamariya", type: "Song", industry: "Bollywood", context: "Action: Waist Shake (Stree)" },
    { title: "Zingaat", type: "Song", industry: "Bollywood", context: "Step: Jumping Wildly" },
    { title: "Mungda", type: "Song", industry: "Bollywood", context: "Action: Gold Jewellery / Total Dhamaal" },
    { title: "Gud Naal Ishq Mitha", type: "Song", industry: "Bollywood", context: "Action: Eating Jaggery (Gud) / Sweets" },
    { title: "Photo", type: "Song", industry: "Bollywood", context: "Action: Taking a picture / Luka Chuppi" },
    { title: "Duniyaa", type: "Song", industry: "Bollywood", context: "Action: Pointing to World / Globe" },
    { title: "Ve Maahi", type: "Song", industry: "Bollywood", context: "Action: Calling Lover / Kesari" },
    { title: "The Jawaani Song", type: "Song", industry: "Bollywood", context: "Action: SOTY 2 / Youth" },
    { title: "Hauli Hauli", type: "Song", industry: "Bollywood", context: "Action: Slowly Slowly / De De Pyaar De" },
    { title: "Shaitan Ka Saala", type: "Song", industry: "Bollywood", context: "Step: The Bala 'Head' Step" },
    { title: "Sauda Khara Khara", type: "Song", industry: "Bollywood", context: "Action: Bhangra / Nagin Hands" },
    { title: "Chandigarh Mein", type: "Song", industry: "Bollywood", context: "Action: Pointing North / Good Newwz" },
    { title: "Haan Main Galat", type: "Song", industry: "Bollywood", context: "Step: The Twist Step (Love Aaj Kal 2)" },
    { title: "Dus Bahane 2.0", type: "Song", industry: "Bollywood", context: "Action: Showing 10 Fingers" },
    { title: "Burj Khalifa", type: "Song", industry: "Bollywood", context: "Action: Pointing up tall building" },
    { title: "Nadiyon Paar", type: "Song", industry: "Bollywood", context: "Step: Janhvi Kapoor Hand Roll" },
    { title: "Panghat", type: "Song", industry: "Bollywood", context: "Action: River bank / Fetching water" },
    { title: "Param Sundari", type: "Song", industry: "Bollywood", context: "Action: Winking / Acting Beautiful" },
    { title: "Raataan Lambiyan", type: "Song", industry: "Bollywood", context: "Action: Sleeping / Long Nights" },
    { title: "Jugnu", type: "Song", industry: "Bollywood", context: "Action: Firefly / Flashlight" },
    { title: "Coka 2.0", type: "Song", industry: "Bollywood", context: "Action: Pointing to Nose (Nose pin) / Coke" },
    { title: "Bhool Bhulaiyaa 2 Title", type: "Song", industry: "Bollywood", context: "Step: Leg Glide / Zig Zag" },
    { title: "Rangisari", type: "Song", industry: "Bollywood", context: "Action: Holi Colors / JugJugg Jeeyo" },
    { title: "Nach Punjaban", type: "Song", industry: "Bollywood", context: "Step: Hand on Chest + Fist Roll" },
    { title: "Dance Ka Bhoot", type: "Song", industry: "Bollywood", context: "Action: Acting possessed by dance" },
    { title: "Manike", type: "Song", industry: "Bollywood", context: "Action: Sri Lankan Vibe / Nora Fatehi" },
    { title: "Thumkeshwari", type: "Song", industry: "Bollywood", context: "Action: Hip Shake / Saree (Bhediya)" },
    { title: "Jedha Nasha", type: "Song", industry: "Bollywood", context: "Action: Acting Dizzy / Intoxicated" },
    { title: "Jungle Mein Kaand", type: "Song", industry: "Bollywood", context: "Action: Wolf Howl / Bhediya" },
    { title: "Show Me The Thumka", type: "Song", industry: "Bollywood", context: "Action: Hip Shake (TJMM)" },
    { title: "Tum Kya Mile", type: "Song", industry: "Bollywood", context: "Action: Spinning in Snow (Rocky Rani)" },
    { title: "What Jhumka", type: "Song", industry: "Bollywood", context: "Step: Alia Bhatt Earring Fall" },
    { title: "Kudmayi", type: "Song", industry: "Bollywood", context: "Action: Wedding / Marriage Ceremony" },
    { title: "Heart Throb", type: "Song", industry: "Bollywood", context: "Action: Beating Heart / Ranveer" },
    { title: "Lutt Putt Gaya", type: "Song", industry: "Bollywood", context: "Action: Falling Down / SRK (Dunki)" },
    { title: "Sher Khul Gaye", type: "Song", industry: "Bollywood", context: "Action: Lion Roar / Hrithik (Fighter)" },
    { title: "Ishq Jaisa Kuch", type: "Song", industry: "Bollywood", context: "Action: Beach / Waves (Fighter)" },
    { title: "Pehle Bhi Main", type: "Song", industry: "Bollywood", context: "Action: Guitar / Rockstar Vibe (Animal)" },
    { title: "Akhiyaan Gulaab", type: "Song", industry: "Bollywood", context: "Action: Rose + Eyes / Smoking" },
    { title: "Arjan Vailly", type: "Song", industry: "Bollywood", context: "Action: Axe Fighting / Animal" },
    { title: "Badtameez Dil", type: "Song", industry: "Bollywood", context: "Action: Spanking Heart" },
    { title: "Dilli 6", type: "Song", industry: "Bollywood", context: "Action: Flying like a pigeon" },
    { title: "Maahi Ve", type: "Song", industry: "Bollywood", context: "Action: Hand Roll Disco (Kal Ho Naa Ho)" },
    { title: "Dupatta Tera Satrangi Da", type: "Song", industry: "Bollywood", context: "Action: Waving a Scarf (Partner)" },
    { title: "Just Chill", type: "Song", industry: "Bollywood", context: "Action: 'Cool' hand gesture / Fan" },
    { title: "Dil Dooba", type: "Song", industry: "Bollywood", context: "Action: Drowning Heart / Khakee" },
    { title: "Beedi", type: "Song", industry: "Bollywood", context: "Action: Lighting a Beedi / Omkara" },
    { title: "Dhoom Again", type: "Song", industry: "Bollywood", context: "Action: Revving Bike / Hrithik" },
    { title: "Character Dheela", type: "Song", industry: "Bollywood", context: "Action: Loose Collar / Salman" },
    { title: "Sunny Sunny", type: "Song", industry: "Bollywood", context: "Action: Sun / Blue Water / Honey Singh" },
    { title: "Abhi Toh Party Shuru Hui Hai", type: "Song", industry: "Bollywood", context: "Action: Checking Watch / Badshah" },
    { title: "Kar Gayi Chull", type: "Song", industry: "Bollywood", context: "Action: Driving Car / Kapoor & Sons" },
    { title: "Nashe Si Chadh Gayi", type: "Song", industry: "Bollywood", context: "Action: Acting Drunk / Befikre" },
    { title: "Dil Chori", type: "Song", industry: "Bollywood", context: "Action: Stealing Heart / Yo Yo Honey Singh" },
    { title: "Illegal Weapon", type: "Song", industry: "Bollywood", context: "Action: Shooting Gun / Street Dancer" },
    { title: "Garmi", type: "Song", industry: "Bollywood", context: "Action: Fanning self / Floor drop" },
    { title: "Tera Hone Laga Hoon", type: "Song", industry: "Bollywood", context: "Action: Falling in love / Atif Aslam" },
    { title: "Pee Loon", type: "Song", industry: "Bollywood", context: "Action: Drinking / Once Upon A Time" },
    { title: "Tum Jo Aaye", type: "Song", industry: "Bollywood", context: "Action: Clapping / Qawwali / Welcome" },
    { title: "Mere Brother Ki Dulhan", type: "Song", industry: "Bollywood", context: "Action: Matrimonial Ad / Binoculars" },
    { title: "Dhating Naach", type: "Song", industry: "Bollywood", context: "Action: Crazy Dance / Phata Poster" },
    { title: "Saree Ke Fall Sa", type: "Song", industry: "Bollywood", context: "Action: Saree Pallu / Matching" },

    // --- 100+ SUPER MAINSTREAM BANGLA SONGS (Nostalgia & Viral) ---
    { title: "Pore Na Chokher Polok", type: "Song", industry: "Bangla", context: "Action: Staring unblinkingly (Polok pore na)" },
    { title: "Amar Gorur Garite", type: "Song", industry: "Bangla", context: "Action: Driving a Bullock Cart (Moo + Drive)" },
    { title: "O Amar Bondhu Go", type: "Song", industry: "Bangla", context: "Action: Handshake / Hugging Friend (Salman Shah)" },
    { title: "Ammajan", type: "Song", industry: "Bangla", context: "Action: Salute + Rocking Baby (Manna)" },
    { title: "Premer Shomadi Bhenge", type: "Song", industry: "Bangla", context: "Action: Falling down + Hugging Tree (Bappa Raj)" },
    { title: "Neela", type: "Song", industry: "Bangla", context: "Action: Pointing to Blue color / Telephone" },
    { title: "Firiye Dao", type: "Song", industry: "Bangla", context: "Action: 'Give it back' hand gesture (Miles)" },
    { title: "Beder Meye Josna", type: "Song", industry: "Bangla", context: "Action: Playing Snake Charmer Flute (Bin)" },
    { title: "Khairun Lo", type: "Song", industry: "Bangla", context: "Action: Long Hair / Red Ribbon (Momtaz)" },
    { title: "Nantu Ghotok", type: "Song", industry: "Bangla", context: "Action: Matchmaker / Connecting two people" },
    { title: "Bondhu Tin Din", type: "Song", industry: "Bangla", context: "Action: Showing 3 fingers + Knocking door" },
    { title: "O Bondhu Lal Golapi", type: "Song", industry: "Bangla", context: "Action: Running (18 always thake doure)" },
    { title: "Ekta Chilo Sonar Konna", type: "Song", industry: "Bangla", context: "Action: Pointing Gold (Ring) + Girl" },
    { title: "Sada Sada Kala Kala", type: "Song", industry: "Bangla", context: "Action: Pointing White & Black / Mandolin" },
    { title: "Oporadhi", type: "Song", industry: "Bangla", context: "Action: Pointing Criminal / Guilty (Arman Alif)" },
    { title: "Noya Daman", type: "Song", industry: "Bangla", context: "Action: New Groom / Sylheti Dance" },
    { title: "Faissha Gechi", type: "Song", industry: "Bangla", context: "Action: Trapped / Cage / Hyder Husyn" },
    { title: "Pagla Hawar Tore", type: "Song", industry: "Bangla", context: "Action: Crazy Wind / Messy Hair (James)" },
    { title: "Hashimukh", type: "Song", industry: "Bangla", context: "Action: Smiling Face (Shironamhin)" },
    { title: "Bondhu Jokhon Bou Loia", type: "Song", industry: "Bangla", context: "Action: Friend + Wife + Fainting" },
    { title: "School Khuleche Re Mowla", type: "Song", industry: "Bangla", context: "Action: Bag on back / Ringing Bell" },
    { title: "Coffee House", type: "Song", industry: "Bangla", context: "Action: Drinking Coffee / Chatting (Manna Dey)" },
    { title: "Majhi Nao Chaira De", type: "Song", industry: "Bangla", context: "Action: Rowing a Boat (Majhi)" },
    { title: "Krishno Aila Radhar Kunje", type: "Song", industry: "Bangla", context: "Action: Flute / Peacock Feather" },
    { title: "Sadher Lau", type: "Song", industry: "Bangla", context: "Action: Holding a big vegetable (Gourd/Lau)" },
    { title: "Premer Mora Jole Dube Na", type: "Song", industry: "Bangla", context: "Action: Dead body floating / Not sinking" },
    { title: "Chumki Choleche Eka Pothe", type: "Song", industry: "Bangla", context: "Action: Catwalk / Walking Alone" },
    { title: "Ore Nil Doriya", type: "Song", industry: "Bangla", context: "Action: Waves (River) / Blue" },
    { title: "Haire Manush Rongin Fanush", type: "Song", industry: "Bangla", context: "Action: Balloon flying up" },
    { title: "Danpithe", type: "Song", industry: "Bangla", context: "Action: Naughty Kid / Running (Minar)" },
    { title: "Tumi Chaile Brishti", type: "Song", industry: "Bangla", context: "Action: Rain falling / Wanting" },
    { title: "Ekhon To Somoy Bhalobashar", type: "Song", industry: "Bangla", context: "Action: Tapping Watch (Time) + Heart" },
    { title: "Shagorer Motoi Gobhir", type: "Song", industry: "Bangla", context: "Action: Deep Ocean / Diving (Salman Shah)" },
    { title: "Priya Amar Priya", type: "Song", industry: "Bangla", context: "Action: Pointing Lover / Shakib Khan" },
    { title: "Number One Shakib Khan", type: "Song", industry: "Bangla", context: "Action: Showing Index Finger (No. 1)" },
    { title: "Cholo Niralay", type: "Song", industry: "Bangla", context: "Action: Shhh (Quiet) / Walking away" },
    { title: "Jao Pakhi Bolo Tare", type: "Song", industry: "Bangla", context: "Action: Flying Bird + Speaking" },
    { title: "Dushtu Kokil", type: "Song", industry: "Bangla", context: "Action: Bird (Cuckoo) / Naughty finger" },
    { title: "Gari Chole Na", type: "Song", industry: "Bangla", context: "Action: Broken Car / Steering stuck" },
    { title: "Boshonto Batase", type: "Song", industry: "Bangla", context: "Action: Blowing wind / Friend" },
    { title: "Sona Bondhu Tui Amare", type: "Song", industry: "Bangla", context: "Action: Pointing Friend + Crazy" },
    { title: "De De Pal Tule De", type: "Song", industry: "Bangla", context: "Action: Hoisting a Sail (Boat)" },
    { title: "Local Bus", type: "Song", industry: "Bangla", context: "Action: Holding rod in bus / Bumping" },
    { title: "Ek Paye Nupur", type: "Song", industry: "Bangla", context: "Action: Pointing to one ankle (Anklet)" },
    { title: "Teer Hara Ei Dheu", type: "Song", industry: "Bangla", context: "Action: Waves / Lost at sea" },
    { title: "Mora Ekti Phul Ke", type: "Song", industry: "Bangla", context: "Action: Saving a flower" },
    { title: "Salam Salam Hajar Salam", type: "Song", industry: "Bangla", context: "Action: Saluting repeatedly" },
    { title: "Ami Banglay Gaan Gai", type: "Song", industry: "Bangla", context: "Action: Singing (Mic) + Map of Bengal" },
    { title: "Melay Jaire", type: "Song", industry: "Bangla", context: "Action: Walking to Fair / Eating Ice cream" },
    { title: "Brishti Pore Tapur Tupur", type: "Song", industry: "Bangla", context: "Action: Rain fingers / Rhythm" },
    { title: "Ei Poth Jodi Na Shesh Hoy", type: "Song", industry: "Bangla", context: "Action: Riding a Bike (Uttam Kumar style)" },
    { title: "Tumi Mor Jiboner Bhabona", type: "Song", industry: "Bangla", context: "Action: Thinking / Head scratch" },
    { title: "Bhalobasha Dao Bhalobasha Nao", type: "Song", industry: "Bangla", context: "Action: Giving and Taking with hands" },
    { title: "Tip Tip Brishti", type: "Song", industry: "Bangla", context: "Action: Rain falling slowly" },
    { title: "O Re Sampan Wala", type: "Song", industry: "Bangla", context: "Action: Rowing Sampan (Boat)" },
    { title: "Barir Manush Koy Amay Tabij...", type: "Song", industry: "Bangla", context: "Action: House people talking / Tabij" },
    { title: "Tomar Barir Ronger Melay", type: "Song", industry: "Bangla", context: "Action: House + Colors / Lost" },
    { title: "Murir Tin", type: "Song", industry: "Bangla", context: "Action: Old Bus / Beating Tin Box" },
    { title: "Oreh Punjabi Wala", type: "Song", industry: "Bangla", context: "Action: Wearing Punjabi / Dancing" },
    { title: "Bapuram Shapure", type: "Song", industry: "Bangla", context: "Action: Snake Charmer / Hissing" },
    { title: "Chaina Meye", type: "Song", industry: "Bangla", context: "Action: Squinting eyes (Chinese look) / Fan" },
    { title: "Chander Batir Kosom", type: "Song", industry: "Bangla", context: "Action: Swearing by Moonlight (Kosom)" },
    { title: "Beyain Shab", type: "Song", industry: "Bangla", context: "Action: DJ Mixing / Dancing" },
    { title: "Assalamu Alaikum Beyain Shab", type: "Song", industry: "Bangla", context: "Action: Salam / Touching feet" },
    { title: "Buk Chin Chin", type: "Song", industry: "Bangla", context: "Action: Chest Pain / Heartbeat (Nisho)" },
    { title: "Bioscoper Neshai", type: "Song", industry: "Bangla", context: "Action: Rotating Bioscope handle" },
    { title: "Tore Putuler Moto Kore Shajiye", type: "Song", industry: "Bangla", context: "Action: Act as Bride (Kumar Bisshojit)" },


    // --- NEW VIRAL & PARTY ADDITIONS (Matching Vibe) ---
    { title: "Lage Ura Dhura", type: "Song", industry: "Bangla", context: "Action: Spinning Head / Toofan Dance" },
    { title: "Deora", type: "Song", industry: "Bangla", context: "Action: Boat Racing / Coke Studio" },
    { title: "Bondhure", type: "Song", industry: "Bangla", context: "Action: Dancing with Friend (Pritom Hasan)" },
    { title: "Shundori Komola", type: "Song", industry: "Bangla", context: "Action: Dancing / Coke Studio" },
    { title: "Taka O Pakhi", type: "Song", industry: "Bangla", context: "Action: Money (Taka) + Bird (Pakhi)" },
    { title: "Pagol Chara Duniya Chole Na", type: "Song", industry: "Bangla", context: "Action: Acting Crazy / Nishi Kabya" },
    { title: "Bulbuli", type: "Song", industry: "Bangla", context: "Action: Bird / Nazrul Vibe (Coke Studio)" },
    { title: "O Priya Tumi Kothay", type: "Song", industry: "Bangla", context: "Action: Screaming into Mic (Riaz)" },

    
    { title: "Magic Mamoni", type: "Song", industry: "Bangla", context: "Action: Magic Wand / Item Dance" },
    
    
    { title: "Sona Bou Shunsoni Go", type: "Song", industry: "Bangla", context: "Action: Golden Wife / Shy" },
 
 { title: "Reshmi Churi", type: "Song", industry: "Bangla", context: "Action: Showing Bangles on wrist (Kona)" },
  { title: "Nasek Nasek", type: "Song", industry: "Bangla", context: "Action: Headbanging / Coke Studio Dance" },
    
    { title: "Khoka", type: "Song", industry: "Bangla", context: "Action: Small Boy / Guitar (Pritom)" },
    { title: "Ami To Preme Porini", type: "Song", industry: "Bangla", context: "Action: Falling / Shaking Head No" },
    { title: "Biyer Bajna", type: "Song", industry: "Bangla", context: "Action: Playing Drums / Wedding" },
{ title: "Jhumka", type: "Song", industry: "Bangla", context: "Action: Xefer/Muza" },


 { title: "Fet Furudde Tuwar Lai", type: "Song", industry: "Bangla", context: "Action: Rubbing Stomach (Burning) + Pointing You" }, { title: "Head Master", type: "Song", industry: "Bangla", context: "Action: Holding Stick / Adjusting Glasses" }, { title: "Modhu Hoi Hoi Bish Khaila", type: "Song", industry: "Bangla", context: "Action: Eating Honey then Poison (Dying)" },

];

// --- GAME LOGIC ---

let currentList = [];

// Initialize: Reset list and UI
function initGame() {
    currentList = [...masterList]; // Refill the list
    updateCounter();
}

// Reset Button Function
function resetGame() {
    const confirmReset = confirm("Start a new game? This will reset the list.");
    if (confirmReset) {
        initGame();
        // Reset UI to Welcome State
        document.getElementById("main-title").innerText = "Ready?";
        document.getElementById("category-tag").innerText = "New Game";
        document.getElementById("context-info").innerText = "Click Next to start!";
    }
}

function updateCounter() {
    const counterEl = document.getElementById("counter");
    counterEl.innerText = `Remaining: ${currentList.length} / ${masterList.length}`;
}

function getNextItem() {
    if (currentList.length === 0) {
        alert("Game Over! We ran out of names. Resetting game...");
        resetGame(); // Auto-trigger reset logic (without confirm)
        initGame(); // Force refill
        return;
    }

    // 1. Pick a random index
    const randomIndex = Math.floor(Math.random() * currentList.length);
    
    // 2. Get the item
    const item = currentList[randomIndex];

    // 3. Remove it from currentList
    currentList.splice(randomIndex, 1);

    // 4. Update UI
    renderCard(item);
    updateCounter();
}

function renderCard(item) {
    const titleEl = document.getElementById("main-title");
    const tagEl = document.getElementById("category-tag");
    const contextEl = document.getElementById("context-info");

    // Animation: Fade out slightly then update
    const card = document.getElementById("card-display");
    card.style.transform = "scale(0.95)";
    
    setTimeout(() => {
        titleEl.innerText = item.title;
        tagEl.innerText = `${item.industry} ${item.type}`;
        contextEl.innerText = item.context;
        card.style.transform = "scale(1)";
    }, 100);
}

// Start the game logic when page loads
initGame();